### ISSUE TITLE
Is it possible for you to add a description file, I mean readme file. Its so difficult to understand the code. Thanks.

### ISSUE THREAD

**Issue by SUBHAMILA** [gioaudino/PartitionedEliasFano#1]

**Comment by gioaudino** [comment]
Sure, will try and get to it by the end of the week. Is there anything in particular you're interested in?

**Comment by SUBHAMILA** [comment]
Hey, I am basically looking for understanding the working and implementation of partitioned elias fano. I need to implement a research paper, so looking for this. It would be great if you can help me with it. Thanks again.

**Comment by gioaudino** [comment]
I have added a README with some documentation.
Please let me know if this answers all your questions or if you have any other.
